name: Readme Stats
on:
  schedule:
    # Runs at 12am IST
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:  #runs manually  
  push:
    branches:
      - main
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
